const reviews = [
  {
    id: 1,
    name: "Param",
    place: "Waranga",
    image: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJQAwwMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAYEAEBAQEBAAAAAAAAAAAAAAAAAUERIf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AxFAAAAAAAAoCCicUVKKioKioAAqiAKgKgAAACBQAAAUBBUAVOKigAAAIKgiiRQAAPAFAABUVBEUUQAFRRFBIoIAAqAKAAACCoqACAqCigIAAoAAiiogAoAgAAAAogCgAIoCARQUEQAUAEUAAABBUAAAAAAAAEFQFURQAABAFAAAAEVUAEUABAAAAABAAAACKgKoAGIoCKAKIAAKACAAoJVEEAEAACAoAIACigIoAAAAABFSKohAQAAARQAEAAAEAAAABUIKKAAAAAACgAAAiCAoAAAAAAAIoKAgoIACgKAACAKAAgmAAAAAAACoogigAAqlAQIACgAAKP//Z",
    text: "I love Pahal! They help me with my homework and we do fun activities. I learned how to dance!"
  },
  {
    id: 2,
    name: "Sahil",
    place: "Waranga",
    image: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJQAwwMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAYEAEBAQEBAAAAAAAAAAAAAAAAAUERIf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AxFAAAAAAAAoCCicUVKKioKioAAqiAKgKgAAACBQAAAUBBUAVOKigAAAIKgiiRQAAPAFAABUVBEUUQAFRRFBIoIAAqAKAAACCoqACAqCigIAAoAAiiogAoAgAAAAogCgAIoCARQUEQAUAEUAAABBUAAAAAAAAEFQFURQAABAFAAAAEVUAEUABAAAAABAAAACKgKoAGIoCKAKIAAKACAAoJVEEAEAACAoAIACigIoAAAAABFSKohAQAAARQAEAAAEAAAABUIKKAAAAAACgAAAiCAoAAAAAAAIoKAgoIACgKAACAKAAgmAAAAAAACoogigAAqlAQIACgAAKP//Z",
    text: "I love singing at Pahal. The volunteers are so nice and make me feel special. I’m better at school now!"
  },
  {
    id: 3,
    name: "Aayush",
    place: "Waranga",
    image: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJQAwwMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAYEAEBAQEBAAAAAAAAAAAAAAAAAUERIf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AxFAAAAAAAAoCCicUVKKioKioAAqiAKgKgAAACBQAAAUBBUAVOKigAAAIKgiiRQAAPAFAABUVBEUUQAFRRFBIoIAAqAKAAACCoqACAqCigIAAoAAiiogAoAgAAAAogCgAIoCARQUEQAUAEUAAABBUAAAAAAAAEFQFURQAABAFAAAAEVUAEUABAAAAABAAAACKgKoAGIoCKAKIAAKACAAoJVEEAEAACAoAIACigIoAAAAABFSKohAQAAARQAEAAAEAAAABUIKKAAAAAACgAAAiCAoAAAAAAAIoKAgoIACgKAACAKAAgmAAAAAAACoogigAAqlAQIACgAAKP//Z",
    text: "Pahal is amazing! I've made so many new friends and we do cool things like painting and acting in plays. The volunteers teach us in a fun way, and I feel more confident now. I love going to Pahal because it's always exciting and everyone is so friendly."
  },
  {
    id: 4,
    name: "Aditya",
    place: "Waranga",
    image: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJQAwwMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAYEAEBAQEBAAAAAAAAAAAAAAAAAUERIf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AxFAAAAAAAAoCCicUVKKioKioAAqiAKgKgAAACBQAAAUBBUAVOKigAAAIKgiiRQAAPAFAABUVBEUUQAFRRFBIoIAAqAKAAACCoqACAqCigIAAoAAiiogAoAgAAAAogCgAIoCARQUEQAUAEUAAABBUAAAAAAAAEFQFURQAABAFAAAAEVUAEUABAAAAABAAAACKgKoAGIoCKAKIAAKACAAoJVEEAEAACAoAIACigIoAAAAABFSKohAQAAARQAEAAAEAAAABUIKKAAAAAACgAAAiCAoAAAAAAAIoKAgoIACgKAACAKAAgmAAAAAAACoogigAAqlAQIACgAAKP//Z",
    text: "Pahal is so much fun! I like the games and the volunteers are really nice."
  },
  {
    id: 5,
    name: "Vaishnavi",
    place: "Class 6th, Waranga",
    image: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJQAwwMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAYEAEBAQEBAAAAAAAAAAAAAAAAAUERIf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AxFAAAAAAAAoCCicUVKKioKioAAqiAKgKgAAACBQAAAUBBUAVOKigAAAIKgiiRQAAPAFAABUVBEUUQAFRRFBIoIAAqAKAAACCoqACAqCigIAAoAAiiogAoAgAAAAogCgAIoCARQUEQAUAEUAAABBUAAAAAAAAEFQFURQAABAFAAAAEVUAEUABAAAAABAAAACKgKoAGIoCKAKIAAKACAAoJVEEAEAACAoAIACigIoAAAAABFSKohAQAAARQAEAAAEAAAABUIKKAAAAAACgAAAiCAoAAAAAAAIoKAgoIACgKAACAKAAgmAAAAAAACoogigAAqlAQIACgAAKP//Z",
    text: "Hello, I'm Vaishnavi from Class 6th, and thanks to Team Pahal's kind and patient volunteers, learning has become fun and engaging, especially in Mathematics and English."
  }
];



export const value = [
  {
    name: "Integrity",
    value: "Upholding honesty and strong moral principles in all our actions and decisions."
  },
  {
    name: "Empathy",
    value: "Understanding and sharing the feelings of others to create a supportive environment."
  },
  {
    name: "Innovation",
    value: "Constantly seeking new and creative ways to improve and make an impact."
  },
  {
    name: "Collaboration",
    value: "Working together as a team to achieve common goals and mutual success."
  },
  {
    name: "Excellence",
    value: "Striving for the highest quality in all we do, ensuring continuous growth and learning."
  }
];




export default reviews;
